def run():
    print("|%s|" % ("-" * 60))
    print("| type -> python3 Create \t: for generate src/ folder   |")
    print("| type -> python3 Create -c\t: for generate component     |")
    print("| type -> python3 Create -cc\t: for generate coreComponent |")
    print("| type -> python3 Create -cn\t: for generate constant      |")
    print("| type -> python3 Create -cx\t: for generate context       |")
    print("| type -> python3 Create -f\t: for generate fragment      |")
    print("| type -> python3 Create -h\t: for help                   |")
    print("| type -> python3 Create -r\t: for remove src/ folder     |")
    print("| type -> python3 Create -s\t: for generate page          |")
    print("| type -> python3 Create -p\t: for generate component     |")
    print("| type -> python3 Create -u\t: for generate util          |")
    print("|%s|" % ("-" * 60))